#pragma once

#include "DriverCommonD3D12.h"
#include <3rdParty/DirectX-Headers/d3dx12.h>

namespace drv_d3d12
{
	struct GraphicsPipelineStateStream
	{
		CD3DX12_PIPELINE_STATE_STREAM_ROOT_SIGNATURE rootSignature;
		CD3DX12_PIPELINE_STATE_STREAM_INPUT_LAYOUT inputLayout;
		CD3DX12_PIPELINE_STATE_STREAM_PRIMITIVE_TOPOLOGY primitiveTopologyType;
		CD3DX12_PIPELINE_STATE_STREAM_VS vs;
		CD3DX12_PIPELINE_STATE_STREAM_GS gs;
		CD3DX12_PIPELINE_STATE_STREAM_HS hs;
		CD3DX12_PIPELINE_STATE_STREAM_DS ds;
		CD3DX12_PIPELINE_STATE_STREAM_PS ps;
		CD3DX12_PIPELINE_STATE_STREAM_BLEND_DESC blendState;
		CD3DX12_PIPELINE_STATE_STREAM_DEPTH_STENCIL1 depthStencilState;
		CD3DX12_PIPELINE_STATE_STREAM_DEPTH_STENCIL_FORMAT depthStencilFormat;
		CD3DX12_PIPELINE_STATE_STREAM_RASTERIZER rasterizerState;
		CD3DX12_PIPELINE_STATE_STREAM_RENDER_TARGET_FORMATS renderTargetFormats;

		uint64 hash() const;
	};
}